// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: avenegers.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvengerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // The super hero name
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // Real life name
	Movies        []string               `protobuf:"bytes,3,rep,name=movies,proto3" json:"movies,omitempty"`                     // Movies the super hero is featured in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvengerProto) Reset() {
	*x = AvengerProto{}
	mi := &file_avenegers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvengerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvengerProto) ProtoMessage() {}

func (x *AvengerProto) ProtoReflect() protoreflect.Message {
	mi := &file_avenegers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvengerProto.ProtoReflect.Descriptor instead.
func (*AvengerProto) Descriptor() ([]byte, []int) {
	return file_avenegers_proto_rawDescGZIP(), []int{0}
}

func (x *AvengerProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvengerProto) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AvengerProto) GetMovies() []string {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_avenegers_proto protoreflect.FileDescriptor

const file_avenegers_proto_rawDesc = "" +
	"\n" +
	"\x0favenegers.proto\x12\x17bbejeck.chapter_3.proto\"W\n" +
	"\fAvengerProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x16\n" +
	"\x06movies\x18\x03 \x03(\tR\x06moviesB\x19Z\x17example.com/kafka-go;pbb\x06proto3"

var (
	file_avenegers_proto_rawDescOnce sync.Once
	file_avenegers_proto_rawDescData []byte
)

func file_avenegers_proto_rawDescGZIP() []byte {
	file_avenegers_proto_rawDescOnce.Do(func() {
		file_avenegers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avenegers_proto_rawDesc), len(file_avenegers_proto_rawDesc)))
	})
	return file_avenegers_proto_rawDescData
}

var file_avenegers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_avenegers_proto_goTypes = []any{
	(*AvengerProto)(nil), // 0: bbejeck.chapter_3.proto.AvengerProto
}
var file_avenegers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avenegers_proto_init() }
func file_avenegers_proto_init() {
	if File_avenegers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avenegers_proto_rawDesc), len(file_avenegers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avenegers_proto_goTypes,
		DependencyIndexes: file_avenegers_proto_depIdxs,
		MessageInfos:      file_avenegers_proto_msgTypes,
	}.Build()
	File_avenegers_proto = out.File
	file_avenegers_proto_goTypes = nil
	file_avenegers_proto_depIdxs = nil
}
